/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesIndexRouteImport } from './routes/devices/index'
import { Route as DevicesRegisterRouteImport } from './routes/devices/register'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRegisterRoute = DevicesRegisterRouteImport.update({
  id: '/devices/register',
  path: '/devices/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/devices/register': typeof DevicesRegisterRoute
  '/devices/': typeof DevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/devices/register': typeof DevicesRegisterRoute
  '/devices': typeof DevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/devices/register': typeof DevicesRegisterRoute
  '/devices/': typeof DevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/dashboard'
    | '/gallery'
    | '/settings'
    | '/devices/register'
    | '/devices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/dashboard'
    | '/gallery'
    | '/settings'
    | '/devices/register'
    | '/devices'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/dashboard'
    | '/gallery'
    | '/settings'
    | '/devices/register'
    | '/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  SettingsRoute: typeof SettingsRoute
  DevicesRegisterRoute: typeof DevicesRegisterRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/register': {
      id: '/devices/register'
      path: '/devices/register'
      fullPath: '/devices/register'
      preLoaderRoute: typeof DevicesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  SettingsRoute: SettingsRoute,
  DevicesRegisterRoute: DevicesRegisterRoute,
  DevicesIndexRoute: DevicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
